config/routes.rb
Rails.application.routes.draw do
  root 'card_generator#new'
  get 'card_generator', to: 'card_generator#new'
  post 'card_generator', to: 'card_generator#create', as: 'generate_card'
  get 'card_generator/show/', to: 'card_generator#show', as: "show"
  post 'card_generator/show/:file_path', to: 'card_generator#show', as: :show_generated_card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/card_generator_controller.rb
class CardGeneratorController < ApplicationController
  def new
    # Display a form for users to enter their names and select a card template
  end

  def create

    selected_image_path = params[:card_order][:template_path]
    user_name = params[:user_name]
    template_path = params[:card_order][:template_path]

    # Load the card template image using RMagick
    template = Magick::Image.read(template_path).first

    # Add the user's name to the image with the correct font and size
    draw = Magick::Draw.new
    draw.annotate(template, 800, 500, 0, 0, user_name) do |card|
      card.font = 'Cairo-VariableFont_slnt,wght.ttf'
      card.pointsize = 36         # Specify the font size
      card.fill = 'white'        # Specify the font color
      card.gravity = Magick::CenterGravity # Position the text at the center
    end


   # Create a unique filename for the generated image
   file_name = "congratulations_card_#{Time.now.to_i}.png"

   # Save the generated image to the public directory
   file_path = Rails.root.join('public', file_name)
   template.write(file_path)
    
   # Redirect to show with param file_name
   redirect_to action: "show", file_name: file_name

end

def show
  file_path = Rails.root.join('public', params[:file_name])

  if File.exist?(file_path)
    send_file file_path, type: 'image/png', disposition: 'inline'
  else
    flash[:error] = "Image not found"
    redirect_to root_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_generator_helper.rb
module CardGeneratorHelper
end

app/views/card_generator/new.html.erb
<h1>Choose a Picture</h1>
<div id="card_image_container">

<%= form_with(model: @card_order, url: card_generator_path, method: 'post', multipart: true) do |form| %>
  <!-- Your form fields go here -->
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="image-option" data-value="app\assets\images\switch 24port.png">
    <%= image_tag "switch 24port.png" %>
  </div>
  <div class="image-option" data-value="">
   <%= image_tag "switch 24port.png" %>
  </div>
  <input type="hidden" id="selectedImage" name="card_order[template_path]" value="">
  <%= text_field_tag (:user_name) %>
  <%= form.submit 'Generate Card', class: 'btn btn-primary' %>
<% end %>

</div>

app/views/card_generator/show.html.erb
<!-- app/views/card_generator/show.html.erb -->
<h1>Congratulations Card</h1>

<%= image_tag show_generated_card_path(file_path: @file_path), alt: 'Congratulations Card' %>

<%= link_to 'Download Card', show_generated_card_path(file_path: @file_path), class: 'btn btn-primary', download: 'congratulations_card.png' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CongratulationsCards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <script>
    $(document).ready(function () {
      // Handle image selection
      $('.image-option').on('click', function () {
        // Remove active class from all image options
        $('.image-option').removeClass('active');
        // Add active class to the clicked image option
        $(this).addClass('active');
        // Set the selected image path in the hidden input field
        var imagePath = $(this).data('value');
        $('#selectedImage').val(imagePath);
      });
    });
  </script>
    <%= yield %>
  </body>
</html>